apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-svc-lb
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 192.168.250.18
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
