apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: blackwolf292/kubernetes-intro:v1
        name: web
        volumeMounts:
        - name: app
          mountPath: /app
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /index.html
            port: 8000
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          tcpSocket:
            port: 8000
      initContainers:
      - name: web-init
        image: busybox:1.32.1
        volumeMounts:
        - name: app
          mountPath: /app
        command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumes:
      - name: app
        emptyDir: {}
