apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-info-rolebinding
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    namespace: prometheus
roleRef:
  kind: ClusterRole
  name: pod-info
  apiGroup: rbac.authorization.k8s.io
