apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: nginx-monitoring
  labels:
    app: nginx-monitoring
spec:
  namespaceSelector:
    matchNames:
      - nginx-monitoring
  selector:
    matchLabels:
      app: nginx-monitoring
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: metrics
      interval: 10s
